### ISSUE TITLE
Individuelle Objektbenennung / Customize names of objects

### ISSUE THREAD

**Issue by DanDits** [LeonardSchwenk/public-gruppenadressen-generator#5]
Hi there, cool tool, thanks! As far as I see this is not open source so I cannot directly contribute, but I plan to try our this software for an upcoming project. I'll write in English as this is the internet, but you could also answer in German.

So far I'm very happy with what I see. One thing though will be very important for many projects, that is: flexible naming of objects. For example it's very common to have multiple lights in a room. So far they would all be named the same, e.g. "1.OG_Schlafzimmer_Deckenlicht_Schalten". But the there are three different addressable Deckenlichter in that example. Same for Beschattung: it's common for a room to have different Rolladen. Not only because they need to have separate configurations on the actor level but also because it might be wanted to control the shutters depending on the side of the room independently. 

Renaming the generated addresses is of course possible, but kind of kills the purpose and is tedious if there are many associated group addresses.
If you want help on the implementation, feel free to ask, depending on the used technologies I could contribute.

Cheers, Daniel

**Comment by LeonardSchwenk** [comment]
@DanDits 
Hi Daniel,
Thank you for being the first issue creator ! 🌟
We are delighted that you're enjoying it so far 👍🏻 ! Great to hear :) 
While the project is not open source, we still appreciate your offer to contribute. We use this repository, along with the KNX forum, to gather feedback.

**You are right on track !** 

Flexible naming or "Freitextfelder" is the next feature, our highest priority for sure.

We also want to release a roadmap to make it more clear what we are planing on doing next and what we already had in mind.

We also plan to release a roadmap to provide clarity on our upcoming plans and what we've already considered. Since we've just released the first "alpha" version, we wanted to collect as much feedback as possible to ensure we're on the right path!

Cheers,
Leo

**Comment by DanDits** [comment]
Thanks for the reply, I will follow this project and can report my findings and suggestions if you want

**Comment by LeonardSchwenk** [comment]
Thanks for the feedback! Any findings or suggestions are warmly welcomed.

**Comment by LeonardSchwenk** [comment]
@DanDits 
Hi we added individual object naming :).
Does that fit your needs ? 

If yes I would close this issue
![GIF Recording 2023-11-23 at 7 53 03 AM](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/b2f76397-f6d6-4942-9b44-2f820013717f)

**Comment by DanDits** [comment]
Hi, Yeah thanks a lot!
I already tried it out and it works fine. From the UX point of view I would
suggest to have the toggle switch before the name input, that makes using
the UI from left to right more intuitive imo
Cheers, Daniel

LeonardSchwenk ***@***.***> schrieb am Do., 23. Nov. 2023,
07:54:

**Comment by LeonardSchwenk** [comment]
Great to hear 👍🏻 
Totally seems like you're not the only one who thought about this design ! :)

I will close this issue and continue for the UX placing in #27 

Thanks for the input and the fast reply @DanDits
